### ISSUE TITLE
Crashing when clicking a suit path

### ISSUE THREAD

**Issue by igoprofit** [OpenToontownTools/OpenLevelEditor#31]
So the bug is, I open a street go into the Paths, press Street, then I go press Shift+S on the streets to create the paths and when i click it, it crashes.

## Reproduction Steps
Go into Paths, press street, Then shift+s on the street and press it and it crashes.

## Expected behavior
I expected it to just be selected and after it was selected I would of linked them together

## System Info

 - OS: Windows 10 Version 1909

 - Command Line: 
"C:/Panda3D-1.11.0-Py39-x64/python/python.exe" -m pip install -r requirements.txt
:top
"C:/Panda3D-1.11.0-Py39-x64/python/python.exe" -m ttle --hoods GS
pause
goto top

 - Toontown School House

 - Panda Version: I use the Panda3D installation which was included in the readme, 

## Checklist
- [x] Did you read the entirety of the [readme](https://github.com/OpenToontownTools/OpenLevelEditor/blob/master/README.md)?
- [x] - Yes
- [x] Did you check for duplicate issues?
- [x] - No

![goofydna](https://user-images.githubusercontent.com/77880353/105575562-3663d080-5d75-11eb-8654-d3c1dc73a6ab.JPG)

**Comment by drewc5131** [comment]
I need a crash log.

Also ensure you have a visgroup selected, you cant just place them outside of a visgroup.

**Comment by drewc5131** [comment]
I asked a week ago to provide logs, you have not. I will be closing this issue until you do so.
