### ISSUE TITLE
When I click on a suitpoint it crashes 

### ISSUE THREAD

**Issue by GabeTheReallyHappyDog48** [OpenToontownTools/OpenLevelEditor#35]
## System Info

 - OS: 

 - Command Line: 

 - Source of resources

 - Panda Version: 

## Checklist
- [x] Did you read the entirety of the [readme](https://github.com/OpenToontownTools/OpenLevelEditor/blob/master/README.md)?
- [x] Did you check for duplicate issues?

- 

- [
![
![image](https://user-images.githubusercontent.com/75962329/114079989-af949f00-985f-11eb-8ec1-2862e61d492a.png)
]`

**Comment by drewc5131** [comment]
Fill it out properly.
