### ISSUE TITLE
Trace back when loading the bat

### ISSUE THREAD

**Issue by BenHilling** [OpenToontownTools/OpenLevelEditor#37]
Describe the bug
 File "C:\Panda3D-1.11.0-py39-x64\python\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Panda3D-1.11.0-py39-x64\python\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\ttle.py", line 258, in
ToontownLevelEditor().run()
File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\ttle.py", line 146, in init
self.le = LevelEditor.LevelEditor()
File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\toontown\leveleditor\LevelEditor.py", line 103, in init
self.styleManager = LevelStyleManager(NEIGHBORHOODS, NEIGHBORHOOD_CODES)
File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\toontown\leveleditor\LevelStyleManager.py", line 21, in init
self.createWallStyleAttributes()
File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\toontown\leveleditor\LevelStyleManager.py", line 169, in createWallStyleAttributes
self.createWallStyleMenu(neighborhood, attribute.getDict()))
File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\toontown\leveleditor\LevelStyleManager.py", line 252, in createWallStyleMenu
bounds = node.getBounds()
AssertionError: !is_empty() at line 538 of panda/src/pgraph/nodePath.cxx

E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master>pause 
is the traceback

Reproduction Steps
No clue just happens when I launch the bat to run open level editor.

 Expected behavior
to load the editor

## Attachments

No
 System Info

 - OS: Windows 10 latest version

 - Command Line: 
the trace back when it starts so I guess the traceback?
 Specify the source of the resource files you are using (e.g. OpenToontown, Toontown Infinite, Corporate Clash) -->
 Resources from the main download page on the requirements

Specify a precise version of Panda3D. If possible link to the latest commit in your build of Panda3D. Simply saying 1.11.0 does not help, since 1.11.0 is still in development. If you are using the Panda3D installation included in the readme, please specify that. -->
 - Panda Version: 1 from the requirements

## Checklist
- [Yes ] Did you read the entirety of the [readme](https://github.com/OpenToontownTools/OpenLevelEditor/blob/master/README.md)?
- [Yes ] Did you check for duplicate issues?

**Comment by ComradeNapCali** [comment]
It looks like your models are not loading correctly. They should be in the root of the directory.
What where phases were you trying to load?

**Comment by drewc5131** [comment]
The Command Line input is asking for the script INSIDE of the .bat file. Please fill out the forms properly

Also attach an image of your level editor root directory

**Comment by BenHilling** [comment]
Forgot I even opened this sorry for the late reply I'm using the resources from the main page

**Comment by ComradeNapCali** [comment]
> I'm using the resources from the main page
Did you put the resource folders in the root of the level editor repository?
It should be like "root/phase_3", "root/phase_3.5", etc.
There shouldn't be a resources subfolder also.

**Comment by BenHilling** [comment]
Yes.

**Comment by BenHilling** [comment]
![image](https://user-images.githubusercontent.com/50081336/115023023-22cc8f80-9eb6-11eb-8d24-5371cff898aa.png)
![image](https://user-images.githubusercontent.com/50081336/115023031-25c78000-9eb6-11eb-9397-448be3a47da9.png)
![image](https://user-images.githubusercontent.com/50081336/115023059-2eb85180-9eb6-11eb-97a9-82a202b2814f.png)
Thats my root folder

**Comment by BenHilling** [comment]
I have to get rid of the --hoods OT cause no file was made/found called OT not sure if thats doing something

**Comment by BenHilling** [comment]
heres what command prompt says 
![image](https://user-images.githubusercontent.com/50081336/115023350-9373ac00-9eb6-11eb-96c1-73578a951106.png)
![image](https://user-images.githubusercontent.com/50081336/115023363-9a9aba00-9eb6-11eb-9f49-6311b952f814.png)
![image](https://user-images.githubusercontent.com/50081336/115023387-a25a5e80-9eb6-11eb-9ce8-22eaea529058.png)

**Comment by BenHilling** [comment]
Oh my god I just fixed it it turns out I hadnt extracted the phase files for like CL.dna CM.DNA in level editor folder and I didnt select which hood I wanted to load cause OT isnt a hood. I'm so dumb some times

**Comment by BenHilling** [comment]
Although I do wonder how do I load the dna file in game?

**Comment by drewc5131** [comment]
> 
> 
> Oh my god I just fixed it it turns out I hadnt extracted the phase files for like CL.dna CM.DNA in level editor folder and I didnt select which hood I wanted to load cause OT isnt a hood. I'm so dumb some times

Yeah there was an accidental push, that OT hood is something private that wasnt meant to be pushed.
