### ISSUE TITLE
getNumParents Object has no Attribute

### ISSUE THREAD

**Issue by ThePlayerZero** [OpenToontownTools/OpenLevelEditor#41]
## Describe the bug
When I tried to add phase_3.5/dna, it gave me an error called `NoneType` Object has no attribute `getNumParents`

## Reproduction Steps
Open run.bat, go to toolbar, load dna file, and it gives error.

## Expected behavior
Load DNA files properly

## Attachments
[bug.log](https://github.com/OpenToontownTools/OpenLevelEditor/files/9039348/bug.log), [storage_interior.zip](https://github.com/OpenToontownTools/OpenLevelEditor/files/9039377/storage_interior.zip)

## System Info
 - OS: Windows 11 21H2/22000.739

 - Command Line: 
"C:/Panda3D-1.11.0-x64/python/python.exe" -m pip install -r requirements.txt
:top
"C:/Panda3D-1.11.0-x64/python/python.exe" -m ttle --hoods TT
pause
goto top

 - Open-Fantasy (which uses Open-Toontown's Resources

 - Panda Version: Panda3D-1.11.0-py39-64 bit

## Checklist
- [ ] Did you read the entirety of the [readme](https://github.com/OpenToontownTools/OpenLevelEditor/blob/master/README.md)? -- Yes
- [ ] Did you check for duplicate issues? -- Yes

**Comment by rocketprogrammer** [comment]
https://github.com/OpenToontownTools/OpenLevelEditor/issues/39

**Comment by drewc5131** [comment]
> #39

this
